# Generated by Django 3.0.5 on 2020-04-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_auto_20200407_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
