# Generated by Django 3.0.5 on 2020-04-10 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_auto_20200407_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist_app.TaskStatus'),
        ),
    ]
